import { Category } from "../../styleshift/types/store";
import { enableBg, enableBackgroundCss, updateBgImg, updateBgImgPosition } from "../features/background";

export const backgroundCategory: Category = {
	category: "🎴 Background",
	settings: [
		{
			type: "checkbox",
			id: "EnableBackground",
			name: "Enable Background",
			description: "Toggle the entire custom background system. When enabled, you can apply custom images, colors, and blurs to the page background.",
			value: true,
			enableFunction: enableBg,
			enableCss: enableBackgroundCss,
		},
		{
			type: "imageInput",
			id: "BackgroundImageUrl",
			name: "Background Image",
			description: "Upload or paste a URL for your custom background image. This image will be placed behind all YouTube content.",
			value: "https://cdn.wallpapersafari.com/74/55/4dgN3G.jpg",
			maxFileSize: 5000000,
			require: { EnableBackground: true },
		},
		{
			type: "checkbox",
			id: "BackgroundThumbnailMode",
			name: "Use Video Thumbnail",
			description: "Automatically sets the current video's high-resolution thumbnail as the page background. This creates a unique look for every video you watch.",
			value: false,
			enableFunction: updateBgImg,
			require: { EnableBackground: true },
		},
		{
			type: "color",
			id: "BackgroundTintColor",
			name: "Tint Color",
			description: "Applies a color overlay on top of your background image or as a solid background color if no image is used. Useful for improving readability.",
			value: "#0000005e",
			varCss: "--nt-bg-main",
			require: { EnableBackground: true },
		},
		{
			type: "numberSlide",
			id: "BackgroundOpacity",
			name: "Tint Opacity",
			description: "Adjusts how strong the tint color is. Lower values make the background image more visible, while higher values make it more solid.",
			value: 80,
			min: 0,
			max: 100,
			step: 1,
			varCss: "--nt-bg-opacity",
			unit: "",
			require: { EnableBackground: true },
		},
		{
			type: "numberSlide",
			id: "BackgroundBlurAmount",
			name: "Blur Intensity",
			description: "Applies a soft blur effect to the background image. This helps content stand out and creates a more modern, 'frosted glass' aesthetic.",
			value: 10,
			min: 0,
			max: 50,
			step: 1,
			varCss: "--nt-bg-blur-amount",
			require: { EnableBackground: true },
		},
		{
			type: "numberSlide",
			id: "BackgroundImageSize",
			name: "Image Size",
			description: "Scales the background image. 100% covers the screen, while higher values zoom in.",
			value: 100,
			min: 0,
			max: 500,
			step: 5,
			updateFunction: updateBgImg,
			require: { EnableBackground: true },
		},
		{
			type: "numberSlide",
			id: "BackgroundImagePositionX",
			name: "Position X",
			description: "Shifts the background image horizontally. 50% is centered.",
			value: 50,
			min: 0,
			max: 100,
			step: 1,
			updateFunction: updateBgImgPosition,
			require: { EnableBackground: true },
		},
		{
			type: "numberSlide",
			id: "BackgroundImagePositionY",
			name: "Position Y",
			description: "Shifts the background image vertically. 50% is centered.",
			value: 50,
			min: 0,
			max: 100,
			step: 1,
			updateFunction: updateBgImgPosition,
			require: { EnableBackground: true },
		},
		{
			type: "checkbox",
			id: "BackgroundImageRepeat",
			name: "Image Repeat",
			description: "If enabled, the background image will tile/repeat. Best for small patterns or textures.",
			value: false,
			enableCss: `:root { --nt-bg-repeat: repeat; }`,
			disableCss: `:root { --nt-bg-repeat: no-repeat; }`,
			require: { EnableBackground: true },
		},
	],
};
