import { Category } from "../../styleshift/types/store";
import { enableBg, enableBackgroundCss, updateBgImg, updateBgImgPosition } from "../features/background";

export const backgroundCategory: Category = {
	category: "🎴 Background",
	settings: [
		{
			type: "checkbox",
			id: "bgEnable",
			name: "Enable background",
			description: "Toggle background image/tint on or off.",
			value: true,
			enableFunction: enableBg,
			enableCss: enableBackgroundCss,
		},
		{
			type: "color",
			id: "BG",
			name: "Background tint color",
			description:
				"Sets the color and opacity of the page background or the tint applied over an image/video.",
			value: "#0000005e",
			varCss: "--nt-bg-main",
		},
		{
			type: "numberSlide",
			id: "BGO",
			name: "Background opacity",
			description: "Adjusts the opacity of the background tint (0-100%).",
			value: 80,
			min: 0,
			max: 100,
			step: 1,
			varCss: "--nt-bg-opacity",
			unit: "",
		},
		{
			type: "imageInput",
			id: "BGIMG",
			name: "Background image URL",
			description: "URL of the image to use as the page background.",
			value: "https://cdn.wallpapersafari.com/74/55/4dgN3G.jpg",
			maxFileSize: 5000000,
		},
		{
			type: "numberSlide",
			id: "BlurBGAM",
			name: "Background blur",
			description: "Applies a blur effect to the background image/video.",
			value: 10,
			min: 0,
			max: 50,
			step: 1,
			varCss: "--nt-bg-blur-amount",
		},
		{
			type: "numberSlide",
			id: "BackgroundS",
			name: "Background size (%)",
			description: "Adjusts the scale of the background image (percent).",
			value: 100,
			min: 0,
			max: 500,
			step: 5,
			updateFunction: updateBgImg,
		},
		{
			type: "numberSlide",
			id: "BackgroundX",
			name: "Background position X (%)",
			description: "Horizontal position of the background image (0-100%).",
			value: 50,
			min: 0,
			max: 100,
			step: 1,
			updateFunction: updateBgImgPosition,
		},
		{
			type: "numberSlide",
			id: "BackgroundY",
			name: "Background position Y (%)",
			description: "Vertical position of the background image (0-100%).",
			value: 50,
			min: 0,
			max: 100,
			step: 1,
			updateFunction: updateBgImgPosition,
		},
		{
			type: "checkbox",
			id: "Repeat",
			name: "Repeat background image",
			description: "Repeat the background image instead of stretching it.",
			value: false,
			enableCss: `:root { --nt-bg-repeat: repeat; }`,
			disableCss: `:root { --nt-bg-repeat: no-repeat; }`,
		},
		{
			type: "checkbox",
			id: "ThumbBG",
			name: "Thumbnail as background",
			description: "Automatically sets the current video's thumbnail as the page background.",
			value: false,
			enableFunction: updateBgImg,
		},
	],
};
