import { Category } from "../../styleshift/types/styleshiftTypes";
import {
	transparencyLayoutCss,
	videoCenteringCss,
	scrollbarCss,
	shadowsOutlinesCss,
	borderRadiusCss,
	accentIntegrationCss,
	animationsTransitionsCss,
	playerEnhancementsCss,
	uiCleanupCss,
} from "../features/mainCss";

export const enhancedCssCategory: Category = {
	category: { icon: "auto_awesome", label: "Enhanced CSS" },
	settings: [
		{
			type: "checkbox",
			id: "EnableTransparencyLayout",
			name: "Transparency & Layout",
			description: "Enables background transparency for various UI elements and general layout improvements.",
			value: true,
			enableCss: transparencyLayoutCss,
		},
		{
			type: "checkbox",
			id: "EnableVideoCentering",
			name: "Video Centering",
			description: "Centers the video player within the viewport. Essential for the NewTube experience.",
			value: true,
			enableCss: videoCenteringCss,
		},
		{
			type: "checkbox",
			id: "EnableModernScrollbars",
			name: "Modern Scrollbars",
			description: "Replaces default scrollbars with a custom thin design that matches your theme.",
			value: true,
			enableCss: scrollbarCss,
		},
		{
			type: "checkbox",
			id: "EnableShadowsOutlines",
			name: "Professional Shadows",
			description: "Adds subtle shadows and outlines to thumbnails, popups, and other UI components.",
			value: true,
			enableCss: shadowsOutlinesCss,
		},
		{
			type: "checkbox",
			id: "EnableBorderRadius",
			name: "Rounded Design",
			description: "Applies consistent rounding to corners of players, thumbnails, and menus.",
			value: true,
			enableCss: borderRadiusCss,
		},
		{
			type: "checkbox",
			id: "EnableAccentIntegration",
			name: "Accent Integration",
			description: "Ensures your custom theme colors apply to icons, progress bars, and selections.",
			value: true,
			enableCss: accentIntegrationCss,
		},
		{
			type: "checkbox",
			id: "EnableAnimationsTransitions",
			name: "Smooth Transitions",
			description: "Adds fluid transitions and micro-animations to buttons, icons, and menus.",
			value: true,
			enableCss: animationsTransitionsCss,
		},
		{
			type: "checkbox",
			id: "EnablePlayerEnhancements",
			name: "Player Enhancements",
			description: "Improves the video player UI with better controls, gradients, and end-screen tweaks.",
			value: true,
			enableCss: playerEnhancementsCss,
		},
		{
			type: "checkbox",
			id: "EnableUICleanup",
			name: "Interface Cleanup",
			description: "Removes clutter and fixes various styling inconsistencies across YouTube.",
			value: true,
			enableCss: uiCleanupCss,
		},
	],
};
