import { Category } from "../../styleshift/types/store";
import { setupRemoveBlackBars, destroyRemoveBlackBars } from "../features/removeBlackBars";
import { enableVideoBackground, disableVideoBackground, updateVideoBgSettings } from "../features/videoBackground";

const isFirefox = navigator.userAgent.toLowerCase().includes("firefox");

export const experienceCategory: Category = {
	category: "🎬 Experience",
	settings: [
		{
			type: "subText",
			text: "Background Video",
		},
		{
			type: "checkbox",
			id: "VideoBackground",
			name: "Enable Background Video",
			description: "Creates an immersive, cinematic experience by projecting a blurred, ambient version of the current video onto the page background.",
			value: false,
			enableFunction: enableVideoBackground,
			disableFunction: disableVideoBackground,
		},
		{
			type: "dropdown",
			id: "VideoBackgroundRenderEngine",
			name: "Render Engine",
			description: "Select 'GPU' for high-performance hardware acceleration via WebGL, or 'CPU' if you encounter visual glitches.",
			value: "GPU",
			updateFunction: updateVideoBgSettings,
			options: {
				GPU: { name: "GPU (Faster)" },
				CPU: { name: "CPU (Compatible)" },
			},
			require: { VideoBackground: true },
		},
		{
			type: "checkbox",
			id: "VideoBackgroundWorker",
			name: "Worker Thread",
			description: "Runs the background rendering on a separate processing thread to keep the main YouTube interface smooth.",
			value: true,
			enableFunction: updateVideoBgSettings,
			disableFunction: updateVideoBgSettings,
			lock: {
				condition: !isFirefox,
				message: "I didn't want to lock this feature for Firefox only, but Chromium browsers make it really hard to get workers running correctly. Chrome's rendering is already so fast that you won't see much of a performance boost anyway.",
			},
			require: { VideoBackground: true },
		},
		{
			type: "numberSlide",
			id: "VideoBackgroundQuality",
			name: "Resolution",
			description: "Controls the internal resolution of the background effect. Lower values significantly reduce GPU/CPU load.",
			value: 50,
			min: 10,
			max: 100,
			step: 10,
			updateFunction: updateVideoBgSettings,
			require: { VideoBackground: true },
		},
		{
			type: "numberSlide",
			id: "VideoBackgroundBlur",
			name: "Blur Amount",
			description: "Adjusts the strength of the Gaussian blur applied to the background video.",
			value: 30,
			min: 0,
			max: 150,
			step: 1,
			updateFunction: updateVideoBgSettings,
			require: { VideoBackground: true },
		},
		{
			type: "numberSlide",
			id: "VideoBackgroundOpacity",
			name: "Opacity",
			description: "Sets the transparency level of the background effect, allowing it to blend with your page theme.",
			value: 100,
			min: 0,
			max: 100,
			step: 1,
			updateFunction: updateVideoBgSettings,
			require: { VideoBackground: true },
		},
		{
			type: "checkbox",
			id: "VideoBackgroundCheckLag",
			name: "Lag Alert",
			description: "Actively monitors system performance and notifies you if the background effect is causing significant frame drops.",
			value: true,
			enableFunction: updateVideoBgSettings,
			disableFunction: updateVideoBgSettings,
			require: { VideoBackground: true },
		},
		{
			type: "checkbox",
			id: "VideoBackgroundStick",
			name: "Stick to Video",
			description: "Attaches the background effect directly to the video player container instead of filling the entire page.",
			value: false,
			enableFunction: updateVideoBgSettings,
			disableFunction: updateVideoBgSettings,
			require: { VideoBackground: true },
		},
		{
			type: "checkbox",
			id: "VideoBackgroundDebug",
			name: "Debug Info",
			description: "Overlays real-time rendering statistics including FPS, latency, and engine status for troubleshooting.",
			value: false,
			enableFunction: updateVideoBgSettings,
			disableFunction: updateVideoBgSettings,
			require: { VideoBackground: true },
		},

		{
			type: "subText",
			text: "Black Bar Removal",
		},
		{
			type: "checkbox",
			id: "RemoveBlackBars",
			name: "Enable Removal",
			description: "Automatically detects and crops out horizontal black bars (letterboxing) from the top and bottom of videos.",
			value: false,
			enableFunction: setupRemoveBlackBars,
			disableFunction: destroyRemoveBlackBars,
		},
		{
			type: "checkbox",
			id: "RemoveBlackBarsUltrawide",
			name: "Fit Ultrawide",
			description: "Optimizes the cropping logic specifically for ultrawide (21:9) monitors and videos.",
			value: true,
			require: { RemoveBlackBars: true },
		},
		{
			type: "checkbox",
			id: "RemoveBlackBarsWorker",
			name: "Worker Thread",
			description: "Offloads the video analysis to a separate background thread to prevent UI stuttering.",
			value: true,
			lock: {
				condition: !isFirefox,
				message: "I didn't want to lock this feature for Firefox only, but Chromium browsers make it really hard to get workers running correctly.",
			},
			require: { RemoveBlackBars: true },
		},
		{
			type: "checkbox",
			id: "RemoveBlackBarsLazyCheck",
			name: "Lazy Check",
			description: "Improves performance by skipping analysis on some frames.",
			value: false,
			require: { RemoveBlackBars: true },
		},
		{
			type: "numberSlide",
			id: "RemoveBlackBarsLazyAmount",
			name: "Check Interval",
			description: "Adjusts the delay between each black bar analysis. Higher values save more battery.",
			value: 50,
			min: -1,
			max: 200,
			step: 1,
			require: { RemoveBlackBars: true },
		},
	],
};
