import { Category } from "../../styleshift/types/store";
import {
	setupVideoBackground,
	disableVideoBackground,
	updateVideoBgSettings,
} from "../features/videoBackground";

export const videoBackgroundCategory: Category = {
	category: "🎆 Background Video",
	settings: [
		{
			type: "checkbox",
			id: "VDOBG",
			name: "Enable Background Video",
			description: "Uses the current video as the page background. (May impact performance)",
			value: false,
			enableFunction: setupVideoBackground,
			disableFunction: disableVideoBackground,
		},
		{
			type: "numberSlide",
			id: "VideoBGBlur",
			name: "Blur Amount",
			description: "Applies a blur effect to the background video.",
			value: 30,
			min: 0,
			max: 100,
			step: 1,
			updateFunction: updateVideoBgSettings,
		},
		{
			type: "numberSlide",
			id: "VideoBGQuality",
			name: "Quality (%)",
			description: "Adjusts the rendering resolution. Lower values improve performance.",
			value: 50,
			min: 10,
			max: 100,
			step: 10,
			updateFunction: updateVideoBgSettings,
		},
		{
			type: "numberSlide",
			id: "VideoBGBrightness",
			name: "Brightness (%)",
			description: "Adjusts the brightness of the background video.",
			value: 100,
			min: 0,
			max: 200,
			step: 5,
			updateFunction: updateVideoBgSettings,
		},
		{
			type: "numberSlide",
			id: "VideoBGContrast",
			name: "Contrast (%)",
			description: "Adjusts the contrast of the background video.",
			value: 100,
			min: 0,
			max: 200,
			step: 5,
			updateFunction: updateVideoBgSettings,
		},
		{
			type: "numberSlide",
			id: "VideoBGSize",
			name: "Scale / Size",
			description: "Zooms the background video in or out.",
			value: 2.2,
			min: 1,
			max: 4,
			step: 0.1,
			updateFunction: updateVideoBgSettings,
		},
		{
			type: "numberSlide",
			id: "VideoBGSmooth",
			name: "Smooth Frame (Skip)",
			description: "Skips frames to reduce CPU usage. Higher values = less smooth but better performance.",
			value: 1,
			min: 1,
			max: 10,
			step: 1,
			updateFunction: updateVideoBgSettings,
		},
	],
};
