import { Category } from "../../styleshift/types/store";
import { enableVideoBackground, disableVideoBackground, updateVideoBgSettings } from "../features/videoBackground/main";

const isFirefox = navigator.userAgent.toLowerCase().includes("firefox");

export const videoBackgroundCategory: Category = {
	category: { icon: "videocam", label: "Background Video" },
	selector: "#movie_player",
	settings: [
		{
			type: "checkbox",
			id: "VideoBackground",
			name: "Background Video",
			description:
				"Creates an immersive, cinematic experience by projecting a blurred, ambient version of the current video onto the page background. (High resource usage)",
			value: false,
			enableFunction: enableVideoBackground,
			disableFunction: disableVideoBackground,
		},
		{
			type: "dropdown",
			id: "VideoBackgroundRenderEngine",
			name: "Render Engine",
			description:
				"Select 'GPU' for high-performance hardware acceleration via WebGL, or 'CPU' if you encounter visual glitches or stability issues.",
			value: "GPU",
			updateFunction: updateVideoBgSettings,
			options: {
				GPU: {
					name: "GPU (Faster)",
				},
				CPU: {
					name: "CPU (Compatible)",
				},
			},
			require: { VideoBackground: true },
		},
		{
			type: "checkbox",
			id: "VideoBackgroundWorker",
			name: "Worker Thread",
			description:
				"Runs the background rendering on a separate processing thread to keep the main YouTube interface smooth and responsive.",
			value: true,
			enableFunction: updateVideoBgSettings,
			disableFunction: updateVideoBgSettings,
			lock: {
				condition: !isFirefox,
				message: "I didn't want to lock this feature for Firefox only, but Chromium browsers (Chrome, Edge, etc.) are making it really hard to get workers running correctly. Maybe I'm just stupid and can't make it work, but honestly, Chrome's rendering is already so fast that you won't see much of a performance boost anyway.",
			},
			require: { VideoBackground: true },
		},
		{
			type: "checkbox",
			id: "VideoBackgroundCheckLag",
			name: "Lag Alert",
			description:
				"Actively monitors system performance and notifies you if the background effect is causing significant frame drops.",
			value: true,
			enableFunction: updateVideoBgSettings,
			disableFunction: updateVideoBgSettings,
			require: { VideoBackground: true },
		},
		{
			type: "checkbox",
			id: "VideoBackgroundDisableFullscreen",
			name: "Disable in Fullscreen",
			description: "Stops the background effect when the video is in fullscreen mode to save resources.",
			value: true,
			updateFunction: updateVideoBgSettings,
			require: { VideoBackground: true },
		},
		{
			type: "numberSlide",
			id: "VideoBackgroundQuality",
			name: "Resolution",
			description:
				"Controls the internal resolution of the background effect. Lower values significantly reduce GPU/CPU load.",
			value: 50,
			min: 10,
			max: 100,
			step: 10,
			updateFunction: updateVideoBgSettings,
			require: { VideoBackground: true },
		},
		{
			type: "numberSlide",
			id: "VideoBackgroundBlur",
			name: "Blur Amount",
			description: "Adjusts the strength of the Gaussian blur applied to the background video.",
			value: 30,
			min: 0,
			max: 150,
			step: 1,
			updateFunction: updateVideoBgSettings,
			require: { VideoBackground: true },
		},
		{
			type: "numberSlide",
			id: "VideoBackgroundSmooth",
			name: "Smoothing",
			description: "Blends multiple frames together to create a smoother, less flickering ambient effect.",
			value: 10,
			min: 1,
			max: 20,
			step: 1,
			updateFunction: updateVideoBgSettings,
			require: { VideoBackground: true },
		},
		{
			type: "numberSlide",
			id: "VideoBackgroundContrast",
			name: "Contrast",
			description:
				"Enhances or reduces the difference between the light and dark areas of the ambient background.",
			value: 1,
			min: 0,
			max: 4,
			step: 0.2,
			updateFunction: updateVideoBgSettings,
			require: { VideoBackground: true },
		},
		{
			type: "numberSlide",
			id: "VideoBackgroundBrightness",
			name: "Brightness",
			description: "Controls the overall light intensity of the background projection.",
			value: 0.4,
			min: 0,
			max: 4,
			step: 0.2,
			updateFunction: updateVideoBgSettings,
			require: { VideoBackground: true },
		},
		{
			type: "numberSlide",
			id: "VideoBackgroundOpacity",
			name: "Opacity",
			description:
				"Sets the transparency level of the background effect, allowing it to blend with your page theme.",
			value: 100,
			min: 0,
			max: 100,
			step: 1,
			updateFunction: updateVideoBgSettings,
			require: { VideoBackground: true },
		},
		{
			type: "numberSlide",
			id: "VideoBackgroundSize",
			name: "Zoom",
			description: "Adjusts the zoom level of the background video to better fill the viewport edges.",
			value: 2.2,
			min: 1,
			max: 4,
			step: 0.1,
			updateFunction: updateVideoBgSettings,
			require: { VideoBackground: true },
		},
		{
			type: "checkbox",
			id: "VideoBackgroundStick",
			name: "Stick to Video",
			description:
				"Attaches the background effect directly to the video player container instead of filling the entire page.",
			value: false,
			enableFunction: updateVideoBgSettings,
			disableFunction: updateVideoBgSettings,
			require: { VideoBackground: true },
		},
		{
			type: "checkbox",
			id: "VideoBackgroundDebug",
			name: "Debug Info",
			description:
				"Overlays real-time rendering statistics including FPS, latency, and engine status for troubleshooting.",
			value: false,
			enableFunction: updateVideoBgSettings,
			disableFunction: updateVideoBgSettings,
			require: { VideoBackground: true },
		},
	],
};
