import { Category } from "../../styleshift/types/store";
import { setupVideoBackground, disableVideoBackground, updateVideoBgSettings } from "../features/videoBackground";

export const videoBackgroundCategory: Category = {
	category: "🎆 Background Video",
	settings: [
		{
			type: "checkbox",
			id: "VDOBG",
			name: "Enable Background Video",
			description: "Adds a cinematic blurred background using the current video. (Higher resource usage)",
			value: false,
			enableFunction: setupVideoBackground,
			disableFunction: disableVideoBackground,
		},
		{
			type: "checkbox",
			id: "VideoBGCheckLag",
			name: "Performance Alert",
			description: "Shows a notification if the background video is causing lag.",
			value: true,
			enableFunction: updateVideoBgSettings,
			disableFunction: updateVideoBgSettings,
		},
		{
			type: "checkbox",
			id: "VideoBGStick",
			name: "Stick to Video Player",
			description: "Keeps the background directly behind the video player instead of the full page.",
			value: false,
			enableFunction: updateVideoBgSettings,
			disableFunction: updateVideoBgSettings,
		},
		{
			type: "dropdown",
			id: "VideoBGRenderEngine",
			name: "Rendering Method",
			description: "Choose 'GPU' for best performance, or 'CPU' if you experience visual issues.",
			value: "GPU",
			updateFunction: updateVideoBgSettings,
			options: {
				GPU: {
					name: "GPU (Faster)",
				},
				CPU: {
					name: "CPU (Compatible)",
				},
			},
		},
		{
			type: "numberSlide",
			id: "VideoBGQuality",
			name: "Resolution Quality",
			description: "Lower this value if the background video is making your computer lag.",
			value: 50,
			min: 10,
			max: 100,
			step: 10,
			updateFunction: updateVideoBgSettings,
		},
		{
			type: "numberSlide",
			id: "VideoBGBlur",
			name: "Blur Intensity",
			description: "Adjust how blurry the background should be.",
			value: 30,
			min: 0,
			max: 150,
			step: 1,
			updateFunction: updateVideoBgSettings,
		},
		{
			type: "numberSlide",
			id: "VideoBGSmooth",
			name: "Visual Smoothing",
			description: "Blends video frames together to prevent flickering.",
			value: 10,
			min: 1,
			max: 20,
			step: 1,
			updateFunction: updateVideoBgSettings,
		},
		{
			type: "numberSlide",
			id: "VideoBGContrast",
			name: "Contrast",
			description: "Adjust the difference between light and dark areas.",
			value: 1,
			min: 0,
			max: 4,
			step: 0.2,
			updateFunction: updateVideoBgSettings,
		},
		{
			type: "numberSlide",
			id: "VideoBGBrightness",
			name: "Brightness",
			description: "Make the background video lighter or darker.",
			value: 0.4,
			min: 0,
			max: 4,
			step: 0.2,
			updateFunction: updateVideoBgSettings,
		},
		{
			type: "numberSlide",
			id: "VideoBGOpacity",
			name: "Transparency",
			description: "Adjust how see-through the background video is.",
			value: 100,
			min: 0,
			max: 100,
			step: 1,
			updateFunction: updateVideoBgSettings,
		},
		{
			type: "numberSlide",
			id: "VideoBGSize",
			name: "Zoom Level",
			description: "Adjust how much of the video is cropped to fill the background.",
			value: 2.2,
			min: 1,
			max: 4,
			step: 0.1,
			updateFunction: updateVideoBgSettings,
		},
	],
};
