name: 🐛 Bug Report
description: File a bug report to help me improve NewTube
title: "[Bug]: "
labels: ["bug"]
assignees:
     - AzPepoze
body:
     - type: markdown
       attributes:
            value: |
                 Thanks for taking the time to fill out this bug report!
     - type: textarea
       id: what-happened
       attributes:
            label: What happened?
            description: Also tell me, what did you expect to happen?
            placeholder: Tell me what you see!
            value: "A bug happened!"
       validations:
            required: true
     - type: textarea
       id: reproduce
       attributes:
            label: Steps to Reproduce
            description: Please provide detailed steps for reproducing the issue.
            placeholder: |
                 1. Go to '...'
                 2. Click on '....'
                 3. Scroll down to '....'
                 4. See error
     - type: input
       id: version
       attributes:
            label: NewTube Version
            description: What version of NewTube are you running? You can find this in the extension settings.
            placeholder: e.g., 1.2.3
     - type: input
       id: browsers
       attributes:
            label: What browsers are you seeing the problem on?
            placeholder: e.g. Chrome, Firefox, Safari
     - type: input
       id: os
       attributes:
            label: Operating System
            description: What operating system are you meing?
            placeholder: e.g., Windows 11, macOS Sonoma
       validations:
            required: true
     - type: textarea
       id: additional-context
       attributes:
            label: Additional Context (Screenshots or Videos)
            description: Add any other context about the problem here. Screenshots or videos are very helpful!
