export const state = {
	enabled: false,
	canvas: null as HTMLCanvasElement | null,
	ctx: null as CanvasRenderingContext2D | null,
	animationId: null as number | null,
	videoFrameCallbackId: null as number | null,
	lastHeight: 0,
	isChecking: false,
	worker: null as Worker | null,
	workerLoadAttempted: false,
	droppedFrames: 0,
	lastPresentedFrames: 0,
	lastSampleColor: "transparent",
	processLatency: 0,
	startTime: 0,
	lastIntervalTime: 0,
	currentInterval: 0,
	debugContainer: null as HTMLDivElement | null,
	sessionId: 0,
	fullscreenCleanup: null as (() => void) | null,
	isUltraWideMode: false,
};
