import { Category } from "../styleshift/types/store";

const custom_styleshift_items: Category[] = [
	{
		category: "🧪 Test Custom Category",
		editable: true,
		settings: [
			{
				type: "text",
				id: "Test_text",
				html: "<b>Test text</b> with <i>HTML</i> support",
				align: "center",
				font_size: 18,
				editable: true,
			},
			{
				type: "sub_text",
				id: "Test_sub_text",
				text: "This is a sub text test",
				align: "left",
				color: "#00ff00",
				font_size: 14,
				editable: true,
			},
			{
				type: "button",
				id: "Test_button_full",
				name: "Full Test Button",
				description: "Testing button properties",
				icon: "🔥",
				align: "center",
				color: "#ffaa00",
				font_size: 16,
				click_function: 'alert("Button Clicked!")',
				editable: true,
			},
			{
				type: "checkbox",
				id: "Test_checkbox",
				name: "Checkbox Test",
				description: "Testing checkbox functionality",
				value: true,
				enable_function: 'console.log("Enabled")',
				disable_function: 'console.log("Disabled")',
				editable: true,
			},
			{
				type: "number_slide",
				id: "Test_number_slide",
				name: "Slider Test",
				description: "Testing slider properties",
				min: 0,
				max: 200,
				step: 5,
				value: 75,
				unit: "px",
				editable: true,
			},
			{
				type: "dropdown",
				id: "Test_dropdown",
				name: "Dropdown Test",
				description: "Testing dropdown options",
				value: "Option 1",
				options: {
					"Option 1": { enable_function: 'console.log("Opt 1")' },
					"Option 2": { enable_function: 'console.log("Opt 2")' },
					"Option 3": { enable_function: 'console.log("Opt 3")' },
				},
				editable: true,
			},
			{
				type: "color",
				id: "Test_color",
				name: "Color Test",
				description: "Testing color picker",
				show_alpha_slider: true,
				value: "#7f5db7ff",
				editable: true,
			},
			{
				type: "text_input",
				id: "Test_text_input",
				name: "Text Input Test",
				description: "Testing simple text input",
				value: "Hello StyleShift",
				editable: true,
			},
			{
				type: "image_input",
				id: "Test_image_input",
				name: "Image Input Test",
				description: "Testing image selection",
				value: "",
				max_file_size: 5000000,
				editable: true,
			},
			{
				type: "preview_image",
				id: "Test_image_input",
				editable: true,
			},
			{
				type: "custom",
				id: "Test_custom",
				ui_function: 'this_setting_frame.innerHTML = "<div style=\'padding: 20px; background: #333; color: gold; border-radius: 10px;\'>Custom UI Rendered</div>";',
				editable: true,
			},
			{
				type: "combine_settings",
				id: "Test_combine",
				name: "Combine Test",
				description: "Testing combine_settings type",
				sync_id: ["Test_checkbox", "Test_number_slide"],
				editable: true,
			},
		],
	},
];

export function get_styleshift_custom_items() {
	return custom_styleshift_items;
}
