export const state = {
	enabled: false,
	canvas: null as HTMLCanvasElement | null,
	ctx: null as CanvasRenderingContext2D | null,
	hCanvas: null as HTMLCanvasElement | null,
	hCtx: null as CanvasRenderingContext2D | null,
	animationId: null as number | null,
	videoFrameCallbackId: null as number | null,
	lastHeight: 0,
	lastWidth: 0,
	vHeight: 0,
	vWidth: 0,
	isChecking: false,
	worker: null as Worker | null,
	workerLoadAttempted: false,
	droppedFrames: 0,
	lastSampleColorV: "transparent",
	lastSampleColorH: "transparent",
	scanProgress: {
		x: 0,
		y: 5,
		isBottom: false,
		topResult: -1,
		bottomResult: -1,
		heightsFound: [] as (number | "inf")[],
	},
	processLatency: 0,
	startTime: 0,
	lastIntervalTime: 0,
	currentInterval: 0,
	debugContainer: null as HTMLDivElement | null,
	sessionId: 0,
	fullscreenCleanup: null as (() => void) | null,
	navCleanup: null as (() => void) | null,
	isScheduled: false,
	isUltraWideMode: false,
};
