import { Category, Setting } from "../types/store";

export const styleshift_property_list: { [key: string]: string[] } = {
	text: ["type", "id", "html", "text_align", "color", "font_size", "editable"],
	sub_text: ["type", "id", "text", "text_align", "color", "font_size", "editable"],
	button: ["type", "id", "description", "icon", "text_align", "color", "font_size", "click_function", "editable"],
	checkbox: [
		"type",
		"id",
		"name",
		"description",
		"value",
		"constant_css",
		"setup_function",
		"enable_css",
		"enable_function",
		"disable_css",
		"disable_function",
		"editable",
	],
	number_slide: [
		"type",
		"id",
		"name",
		"description",
		"min",
		"max",
		"step",
		"value",
		"var_css",
		"setup_function",
		"constant_css",
		"update_function",
		"editable",
	],
	dropdown: ["type", "id", "name", "description", "value", "constant_css", "setup_function", "options", "editable"],
	color: [
		"type",
		"id",
		"name",
		"description",
		"show_alpha_slider",
		"value",
		"var_css",
		"setup_function",
		"constant_css",
		"update_function",
		"editable",
	],
	image_input: ["type", "id", "name", "description", "value", "max_file_size", "editable"],
	preview_image: ["type", "id", "editable"],
	Custom: ["type", "id", "setup_function", "constant_css", "ui_function"],
	Combine_settings: ["type", "id", "name", "description", "sync_id", "update_function", "editable"],
};

export const styleshift_category_list: Category = { category: "Category", selector: "", rainbow: false, settings: [] };

export const ui_preset: Setting[] = [
	{
		type: "text",
		id: "Test_text",
		html: "Test text",
		text_align: "left",
		font_size: 14,
	},
	{
		type: "sub_text",
		id: "Test_Sub_title",
		text: "Test Setting Sub title",
		text_align: "left",
		color: "#ffffff",
		font_size: 14,
	},
	{
		type: "button",
		id: "Test_button",
		name: "button",
		description: "",
		icon: "",
		text_align: "center",
		color: "#00FF99",
		font_size: 15,
	},
	{
		type: "checkbox",
		id: "Test_checkbox",
		name: "Some checkbox",
		description: "",
		value: false,
	},
	{
		type: "number_slide",
		id: "Test_number_slide",
		name: "Just Number Slide",
		description: "",
		min: 0,
		max: 100,
		step: 1,
		value: 50,
	},
	{
		type: "dropdown",
		id: "Test_dropdown",
		name: "Just dropdown",
		description: "",
		value: "Item_1",
		options: { Item_1: {}, Item_2: {}, Item_3: {} },
	},
	{
		type: "color",
		id: "Test_color",
		name: "Just color Selector",
		description: "",
		show_alpha_slider: true,
		value: "#FF0000FF",
	},
	{
		type: "image_input",
		id: "Test_image_input",
		name: "Just image Input",
		description: "",
		value: "",
		max_file_size: 1000000,
	},
	{
		type: "preview_image",
		id: "",
	},
	{
		type: "custom",
		id: "Test_Custom",
		setup_function: "",
		constant_css: "",
		ui_function: "",
	},
];

export const type_convert_table = {
	function: "js",
	css: "css",
};
