import { Category, Setting } from "../types/styleshiftTypes";

export const styleshiftPropertyList: { [key: string]: string[] } = {
	text: ["type", "id", "html", "align", "color", "fontSize", "editable"],
	subText: ["type", "id", "text", "align", "color", "fontSize", "editable"],
	button: ["type", "id", "description", "icon", "align", "color", "fontSize", "clickFunction", "editable"],
	checkbox: [
		"type",
		"id",
		"name",
		"description",
		"value",
		"constantCss",
		"setupFunction",
		"enableCss",
		"enableFunction",
		"disableCss",
		"disableFunction",
		"editable",
	],
	numberSlide: [
		"type",
		"id",
		"name",
		"description",
		"min",
		"max",
		"step",
		"value",
		"varCss",
		"setupFunction",
		"constantCss",
		"updateFunction",
		"editable",
	],
	dropdown: ["type", "id", "name", "description", "value", "constantCss", "setupFunction", "options", "editable"],
	color: [
		"type",
		"id",
		"name",
		"description",
		"showAlphaSlider",
		"value",
		"varCss",
		"setupFunction",
		"constantCss",
		"updateFunction",
		"editable",
	],
	imageInput: ["type", "id", "name", "description", "value", "maxFileSize", "editable"],
	previewImage: ["type", "id", "editable"],
	Custom: ["type", "id", "setupFunction", "constantCss", "uiFunction"],
	Combine_settings: ["type", "id", "name", "description", "syncId", "updateFunction", "editable"],
};

export const styleshiftCategoryList: Category = { category: "Category", selector: "", rainbow: false, settings: [] };

export const uiPreset: Setting[] = [
	{
		type: "text",
		id: "Test_text",
		html: "Test text",
		align: "left",
		fontSize: 14,
	},
	{
		type: "subText",
		id: "Test_Sub_title",
		text: "Test Setting Sub title",
		align: "left",
		color: "#ffffff",
		fontSize: 14,
	},
	{
		type: "button",
		id: "Test_button",
		name: "button",
		description: "",
		icon: "",
		align: "center",
		color: "#00FF99",
		fontSize: 15,
	},
	{
		type: "checkbox",
		id: "Test_checkbox",
		name: "Some checkbox",
		description: "",
		value: false,
	},
	{
		type: "numberSlide",
		id: "Test_number_slide",
		name: "Just Number Slide",
		description: "",
		min: 0,
		max: 100,
		step: 1,
		value: 50,
	},
	{
		type: "dropdown",
		id: "Test_dropdown",
		name: "Just dropdown",
		description: "",
		value: "Item_1",
		options: { Item_1: {}, Item_2: {}, Item_3: {} },
	},
	{
		type: "color",
		id: "Test_color",
		name: "Just color Selector",
		description: "",
		showAlphaSlider: true,
		value: "#FF0000FF",
	},
	{
		type: "imageInput",
		id: "Test_image_input",
		name: "Just image Input",
		description: "",
		value: "",
		maxFileSize: 1000000,
	},
	{
		type: "previewImage",
		id: "",
	},
	{
		type: "custom",
		id: "Test_Custom",
		setupFunction: "",
		constantCss: "",
		uiFunction: "",
	},
];

export const typeConvertTable = {
	Function: "js",
	Css: "css",
};
